logging_path: /tmp
pipeline_id:

data_path: data/mnist_short.pkl
target_col: label

seed: 2

test_size: 0.2

cnn_config:
  filter_size: 3
  num_filters: 32
  pool_size: 2
  wt_scale: 1
  bias_scale: 1
dim_list: [32,32,10]
activation_list: [relu,sigmoid,softmax]
lr: 0.001
n_epochs: 5
num_batches: 4
loss_str: crossentropy
wts_low: -1
wts_high: 1

save_output: True
