logging_path: /tmp
pipeline_id:

data_path: data/mnist_med.pkl
target_col: label

seed: 2

test_size: 0.2

cnn_config:
  filter_size: 3
  num_filters: 2
  pool_size: 2
  wt_scale: 0.01
  bias_scale: 0.01
dim_list: [64,64,10]
activation_list: [relu,sigmoid,softmax]
lr: 0.001
n_epochs: 5
num_batches: 4
loss_str: crossentropy
wts_low: -0.01
wts_high: 0.01
