logging_path: /tmp
pipeline_id:

data_path: data/exp_sin_reg.csv
target_col: y

seed: 2

test_size: 0.2

dim_list: [256,256,256,1]
activation_list: [relu,relu,relu,identity]
lr: 0.0005
n_epochs: 2000
loss_str: rmse
num_batches: 100
wts_low: -1
wts_high: 1